name: SignolegisRPG
main: io.github.willywonka125.SignolegisRPG.Signolegis
version: 0.2.4
commands:
  signo:
    description: Singolegis administrative command
    usage: /signo help
    aliases: [sg, sig, si]
  quests:
    description: Signolegis quests command
    usage: /quests
    aliases: [q, quest]